# Generated by Django 4.0.1 on 2022-04-13 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoes',
            old_name='name',
            new_name='title',
        ),
    ]
