# Generated by Django 4.0.1 on 2022-04-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_hat_type_alter_jacket_type_alter_pants_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pants',
            name='type',
            field=models.CharField(choices=[('Jeans', 'Jeans'), ('Shorts', 'Shorts'), ('Tracksuit', 'Tracksuit'), ('Pants', 'Pants'), ('Skirt', 'Skirt')], max_length=9),
        ),
        migrations.AlterField(
            model_name='shirt',
            name='type',
            field=models.CharField(choices=[('T-shirt', 'T-shirt'), ('Sweatshirt', 'Sweatshirt'), ('Sweater', 'Sweater'), ('Shirt', 'Shirt'), ('Tank top', 'Tank top')], max_length=10),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='type',
            field=models.CharField(choices=[('Boots', 'Boots'), ('Heels', 'Heels'), ('Sport shoes', 'Sport shoes'), ('Flip flops', 'Flip flops')], max_length=11),
        ),
        migrations.AlterField(
            model_name='underwear',
            name='type',
            field=models.CharField(choices=[('Briefs', 'Briefs'), ('Boxers', 'Boxers'), ('Bra', 'Bra'), ('Thong bikini', 'Thong bikini'), ('Bikini', 'Bikini'), ('Corset', 'Corset')], max_length=12),
        ),
    ]
