# Generated by Django 4.0.1 on 2022-04-13 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_pants_type_alter_shirt_type_alter_shoes_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hat',
            name='name',
        ),
        migrations.RemoveField(
            model_name='jacket',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pants',
            name='name',
        ),
        migrations.RemoveField(
            model_name='shirt',
            name='name',
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='title',
        ),
        migrations.RemoveField(
            model_name='socks',
            name='name',
        ),
        migrations.RemoveField(
            model_name='underwear',
            name='name',
        ),
    ]
