# Generated by Django 4.0.1 on 2022-04-13 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_hat_name_remove_jacket_name_remove_pants_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Kids', 'Kids')], default='Male', max_length=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='shoes',
            name='id',
        ),
        migrations.AddField(
            model_name='shoes',
            name='abstractmodel_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.abstractmodel'),
            preserve_default=False,
        ),
    ]
