# Generated by Django 4.0.1 on 2022-04-13 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_abstractmodel_remove_shoes_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Socks',
        ),
        migrations.DeleteModel(
            name='Underwear',
        ),
        migrations.RemoveField(
            model_name='hat',
            name='id',
        ),
        migrations.RemoveField(
            model_name='jacket',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pants',
            name='id',
        ),
        migrations.RemoveField(
            model_name='shirt',
            name='id',
        ),
        migrations.AddField(
            model_name='abstractmodel',
            name='picture',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hat',
            name='abstractmodel_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.abstractmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jacket',
            name='abstractmodel_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.abstractmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pants',
            name='abstractmodel_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.abstractmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shirt',
            name='abstractmodel_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.abstractmodel'),
            preserve_default=False,
        ),
    ]
