# Generated by Django 4.0.1 on 2022-04-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_abstractmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abstractmodel',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
